//! Phase 3 integration test — Ljung-Box scan golden snapshot (D3-05 / Blocker 4).
//!
//! Loads the precomputed statsmodels 0.14.6 golden from
//! `tests/fixtures/ljung_box_golden.json` (generated by
//! `tests/fixtures/generate_golden.py` — committed alongside this file).
//! Constructs a `BarFrame` whose `close` column matches the JSON's `close`
//! array byte-for-byte (the script dumps the AR(1) input so Rust and Python
//! consume identical f64 bytes — no PRNG drift). Calls `LjungBoxScan::run`
//! directly against a `BufferSink`, parses the resulting envelope, and:
//!
//! 1. Masks the volatile fields (`run_id`, `produced_at_utc`).
//! 2. `insta::assert_json_snapshot!` the masked envelope — creates
//!    `tests/snapshots/scan_ljung_box__ljung_box_matches_statsmodels_golden.snap`
//!    on first run; subsequent runs validate against the committed snapshot.
//! 3. Decodes the base64 `q_stats`, `p_values`, and `acf` arrays from the
//!    envelope and compares element-by-element with the statsmodels golden
//!    within 1e-12 (statsmodels-to-Rust direction, NEVER the inverse).
//!
//! The golden fixture's `provenance.statsmodels_version` is asserted to be
//! exactly `"0.14.6"` so a future version bump that changes the JSON without
//! re-running the Python script fails loudly.

#![allow(
    clippy::cast_precision_loss,
    clippy::too_many_lines, // single-method test walks 8 numbered steps; intentional.
)]

mod common;

use std::collections::BTreeMap;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

use chrono::{Duration, TimeZone, Utc};

use miner_core::aggregator::{BarFrame, Timeframe};
use miner_core::engine::gap_policy::GapPolicyKind;
use miner_core::engine::param_hash;
use miner_core::findings::{Finding, RunId, TimeRange};
use miner_core::reader::{ClosedRangeUtc, Side};
use miner_core::scan::ljung_box::LjungBoxScan;
use miner_core::scan::{Scan, ScanCtx, ScanRequest};

use common::BufferSink;

/// statsmodels golden fixture loaded at test time. The file is committed at
/// `tests/fixtures/ljung_box_golden.json` (Plan 03-06 Task 1 — Blocker 4).
const GOLDEN_JSON: &str = include_str!("fixtures/ljung_box_golden.json");

/// Tolerance for element-by-element f64 comparison against the statsmodels
/// reference. 1e-12 mirrors RESEARCH §"Open Question 2" — the kernels are
/// deterministic single-precision floating-point chains that match
/// statsmodels' double-precision pipeline within this bound for N=256, lags=10.
const FLOAT_TOLERANCE: f64 = 1e-12;

#[test]
fn ljung_box_matches_statsmodels_golden() {
    // Step 1 — load the precomputed statsmodels reference.
    let golden: serde_json::Value =
        serde_json::from_str(GOLDEN_JSON).expect("ljung_box_golden.json must be valid JSON");

    // Provenance gate (Blocker 4 — D3-05 invariant): the JSON MUST cite
    // statsmodels 0.14.6 or the test refuses to run.
    let prov_version = golden["provenance"]["statsmodels_version"].as_str();
    assert_eq!(
        prov_version,
        Some("0.14.6"),
        "ljung_box_golden.json provenance.statsmodels_version must be \"0.14.6\"; got {prov_version:?}. \
         Regenerate via `python3 crates/miner-core/tests/fixtures/generate_golden.py` after installing `statsmodels==0.14.6`.",
    );

    // Step 2 — extract the input close array. This is the SAME f64 bytes the
    // statsmodels script consumed — Rust and Python see identical inputs, so
    // the kernel output difference is bounded by the f64 ops themselves.
    let close: Vec<f64> = golden["close"]
        .as_array()
        .expect("close field present")
        .iter()
        .map(|v| v.as_f64().expect("close element is a number"))
        .collect();
    assert_eq!(close.len(), 256, "Plan 06 golden uses N=256 AR(1) samples");

    // Step 3 — build a BarFrame whose close column matches the JSON. Other
    // columns (open/high/low) are derived trivially; LjungBoxScan reads only
    // `close` and `ts_open_utc`.
    let bars = build_bar_frame_from_closes(&close);

    // Step 4 — construct the ScanRequest + ScanCtx. lags=10 is the fixed
    // golden parameter (matches the Python script's `LAGS = 10`).
    let resolved_params = serde_json::json!({"lags": 10});
    let param_hash = param_hash::param_hash(&resolved_params).expect("param_hash ok");
    let window_start = Utc.with_ymd_and_hms(2024, 1, 1, 0, 0, 0).unwrap();
    let window_end = Utc.with_ymd_and_hms(2024, 1, 4, 0, 0, 0).unwrap();
    let req = ScanRequest {
        scan_id: "stats.autocorr.ljung_box".into(),
        version: 1,
        instrument: "EURUSD".into(),
        side: Side::Bid,
        timeframe: Timeframe::Tf15m,
        window: ClosedRangeUtc {
            start: window_start,
            end: window_end,
        },
        sub_range: TimeRange {
            start_utc: window_start,
            end_utc: window_end,
        },
        gap_policy: GapPolicyKind::ContinuousOnly,
        resolved_params,
        param_hash,
        dry_run: false,
        sleep_after_first_finding_ms: None,
    };
    let ctx = ScanCtx {
        bars: &bars,
        gap_manifest: None,
        run_id: RunId::new(),
        code_revision: "test-rev-abc1234",
        cancel: Arc::new(AtomicBool::new(false)),
        sleep_after_first_finding_ms: None,
    };

    let mut sink = BufferSink::new();

    // Step 5 — dispatch the scan. LjungBoxScan emits exactly one
    // Finding::Result envelope.
    LjungBoxScan
        .run(&ctx, &req, &mut sink)
        .expect("LjungBoxScan::run ok");

    // Step 6 — parse the captured envelope.
    let findings = common::parse_findings(&sink.0);
    assert_eq!(findings.len(), 1, "exactly one envelope emitted");
    let Finding::Result(ref r) = findings[0] else {
        panic!("expected Finding::Result; got {:?}", findings[0]);
    };

    // Step 7 — element-by-element comparison against the statsmodels golden.
    let golden_q_stats: Vec<f64> = golden["q_stats"]
        .as_array()
        .expect("q_stats present")
        .iter()
        .map(|v| v.as_f64().expect("q_stat is f64"))
        .collect();
    let golden_p_values: Vec<f64> = golden["p_values"]
        .as_array()
        .expect("p_values present")
        .iter()
        .map(|v| v.as_f64().expect("p_value is f64"))
        .collect();
    let golden_acf: Vec<f64> = golden["acf"]
        .as_array()
        .expect("acf present")
        .iter()
        .map(|v| v.as_f64().expect("acf is f64"))
        .collect();

    let rust_q_stats = decode_f64_raw_array(&r.effect.extra, "q_stats");
    let rust_p_values = decode_f64_raw_array(&r.effect.extra, "p_values");
    let rust_acf = decode_f64_raw_array(&r.effect.extra, "acf");

    assert_close(
        &rust_q_stats,
        &golden_q_stats,
        FLOAT_TOLERANCE,
        "q_stats vs statsmodels",
    );
    assert_close(
        &rust_p_values,
        &golden_p_values,
        FLOAT_TOLERANCE,
        "p_values vs statsmodels",
    );
    assert_close(
        &rust_acf,
        &golden_acf,
        FLOAT_TOLERANCE,
        "acf vs statsmodels",
    );

    // Step 8 — insta snapshot of the masked envelope shape. The float arrays
    // round-trip as Base64 strings in the snapshot; structural changes
    // (additional fields, renames) will flag a diff.
    let mut masked = serde_json::to_value(&findings[0]).expect("envelope -> Value");
    common::mask_volatile_fields(&mut masked);
    insta::assert_json_snapshot!("ljung_box_matches_statsmodels_golden", masked);
}

/// Construct a `BarFrame` whose `close` column matches the supplied f64
/// sequence verbatim. Other columns are derived for OHLC well-formedness;
/// `LjungBoxScan` reads only `close` and `ts_open_utc`. Timestamps are 15m
/// apart starting at 2024-01-01 UTC so the per-return `timestamps_ms` array
/// in the Result is non-trivial.
fn build_bar_frame_from_closes(close: &[f64]) -> BarFrame {
    let start = Utc.with_ymd_and_hms(2024, 1, 1, 0, 0, 0).unwrap();
    let n = close.len();
    let ts_open: Vec<chrono::DateTime<Utc>> = (0..n)
        .map(|i| {
            let i_i64 = i64::try_from(i).expect("fits in i64");
            start + Duration::minutes(15 * i_i64)
        })
        .collect();
    let ts_close: Vec<chrono::DateTime<Utc>> =
        ts_open.iter().map(|t| *t + Duration::minutes(15)).collect();
    let opens: Vec<f64> = close.to_vec();
    let highs: Vec<f64> = close.iter().map(|c| c + 0.001).collect();
    let lows: Vec<f64> = close.iter().map(|c| c - 0.001).collect();
    let vols = vec![1.0; n];
    BarFrame {
        source_id: "dukascopy".into(),
        symbol: "EURUSD".into(),
        side: Side::Bid,
        tf: Timeframe::Tf15m,
        ts_open_utc: ts_open,
        ts_close_utc: ts_close,
        open: opens,
        high: highs,
        low: lows,
        close: close.to_vec(),
        tick_volume: vols,
    }
}

/// Decode an `effect.extra[name]` `RawArray` from a parsed `ResultFinding`
/// into a `Vec<f64>`. The wire form is base64-encoded LE f64 bytes
/// (D-01); we inverse the encoding here so the test can compare against
/// the statsmodels JSON's plain float arrays.
fn decode_f64_raw_array(
    extra: &BTreeMap<String, miner_core::findings::RawArray>,
    key: &str,
) -> Vec<f64> {
    let arr = extra
        .get(key)
        .unwrap_or_else(|| panic!("extra[{key}] present"));
    let bytes = &arr.data.0;
    assert_eq!(
        bytes.len() % 8,
        0,
        "{key}: byte length must be a multiple of 8"
    );
    let mut out = Vec::with_capacity(bytes.len() / 8);
    for chunk in bytes.chunks_exact(8) {
        let mut buf = [0u8; 8];
        buf.copy_from_slice(chunk);
        out.push(f64::from_le_bytes(buf));
    }
    out
}

fn assert_close(actual: &[f64], expected: &[f64], tol: f64, label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch (actual {}, expected {})",
        actual.len(),
        expected.len(),
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (a - e).abs();
        assert!(
            diff <= tol,
            "{label}[{i}]: |{a} - {e}| = {diff:.3e} exceeds tolerance {tol:.3e}",
        );
    }
}
